### ISSUE TITLE
Use single encoder for different structs

### ISSUE THREAD

**Issue by vkuznet** [bet365/jingo#27]
Hi,
I have a feature request. So far you provide encoder for individual struct and then use it for serialization. But what if my code contains hundred of structs (it is not uncommon when you work with large DBs), then your design forces me to create the same amount of encoders, while standard library I still use single `json.Marshal` method for all my structs. Can code be generalized to use any struct passed to single encoder. May be this part can be added when generics can be in place?

**Comment by kungfusheep** [comment]
Hi

Whilst this isn't something that would be built into jingo, it is possible to write something like the below, based on how the code would be used in your software (the below isn't safe for concurrent access, for example). This would avoid the need to create an encoder per struct manually if that was a burden - but would obviously have some overhead compared to using an encoder directly. 

```go
lookup := make(map[reflect.Type]*jingo.StructEncoder)
func getEncoder(s interface{}) *jingo.StructEncoder {
	rt := reflect.TypeOf(s)

	if en, ok := lookup[rt]; ok {
		return en
	}
	enc := jingo.NewStructEncoder(s)
	lookup[rt] = enc
	return enc
}
```

You could then use it like so ( you might even wrap up the Marshal call into a single function ... )
```go
e := getEnc(myStruct)
e.Marshal(&myStruct, b)

e = getEnc(myOtherStruct)
e.Marshal(&myOtherStruct, b)
```
Because of the way jingo works it is not possible to have a single encoder which supports all structs due to it computing a lot of the workload up-front, but this approach does get you close. 

Thanks
